# Default initial positions for dummy2-dual-gripperv2's ros2_control fake system

initial_positions:
  left_figer1: 0
  left_figer2: 0
  left_joint1: 0
  left_joint2: 0
  left_joint3: 0
  left_joint4: 0
  left_joint5: 0
  left_joint6: 0
  right_figer1: 0
  right_figer2: 0
  right_joint1: 0
  right_joint2: 0
  right_joint3: 0
  right_joint4: 0
  right_joint5: 0
  right_joint6: 0