# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    dummy2_right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    dummy2_right_hand_controller:
      type: position_controllers/GripperActionController


    dummy2_left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    dummy2_left_hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dummy2_right_arm_controller:
  ros__parameters:
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
dummy2_right_hand_controller:
  ros__parameters:
    joint: right_joint6
dummy2_left_arm_controller:
  ros__parameters:
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
dummy2_left_hand_controller:
  ros__parameters:
    joint: left_joint6