# Default initial positions for dummy2-gripperv2's ros2_control fake system

initial_positions:
  camera: 0
  camera_eye: 0
  figer1: 0
  figer2: 0
  joint1: 0
  joint2: 0
  joint3: 0
  joint4: 0
  joint5: 0
  joint6: 0