# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - dummy2_arm_controller
    - dummy2_hand_controller

  dummy2_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - camera
      - camera_eye
  dummy2_hand_controller:
    type: FollowJointTrajectory
    joints:
      - joint6
      - figer1
      - figer2