# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    dummy2_arm:
      type: joint_trajectory_controller/JointTrajectoryController


    dummy2_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    dummy2_hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dummy2_arm:
  ros__parameters:
    joints:
      []
    command_interfaces:
      []
    state_interfaces:
      []
dummy2_arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - camera
      - camera_eye
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
dummy2_hand_controller:
  ros__parameters:
    joint: joint6